import 'dotenv/config';
import express from 'express';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const __filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename);
const app=express(),port=Number(process.env.PORT||3000),OPENAI_URL='https://api.openai.com/v1/responses';
app.use(express.json({limit:'25mb'}));app.use(express.static(__dirname));
function key(){if(!process.env.OPENAI_API_KEY||process.env.OPENAI_API_KEY.includes('PASTE_'))throw Error('OPENAI_API_KEY не задан в .env');return process.env.OPENAI_API_KEY}
function model(){if(!process.env.OPENAI_MODEL||process.env.OPENAI_MODEL.includes('YOUR_'))throw Error('OPENAI_MODEL не задан в .env');return process.env.OPENAI_MODEL}
function text(d){if(d.output_text)return d.output_text;return(d.output||[]).flatMap(x=>x.content||[]).map(x=>x.text||'').join('')}
async function ai({instructions,input,name,schema}){const r=await fetch(OPENAI_URL,{method:'POST',headers:{Authorization:`Bearer ${key()}`,'Content-Type':'application/json'},body:JSON.stringify({model:model(),instructions,input,text:{format:{type:'json_schema',name,strict:true,schema}}})});const raw=await r.text();let d;try{d=JSON.parse(raw)}catch{throw Error(raw.slice(0,600))}if(!r.ok)throw Error(d?.error?.message||`OpenAI HTTP ${r.status}`);const t=text(d);if(!t)throw Error('OpenAI не вернул результат');try{return JSON.parse(t)}catch{throw Error(`Некорректный JSON от AI: ${t.slice(0,500)}`)}}
const clothingSchema={type:'object',additionalProperties:false,properties:{name:{type:'string'},category:{type:'string',enum:['Верх','Низ','Обувь','Верхняя одежда','Аксессуары','Другое']},type:{type:'string'},color:{type:'string'},style:{type:'string'},season:{type:'string',enum:['Лето','Весна','Осень','Зима','Демисезон','Всесезон']},material:{type:'string'},warmth:{type:'number'},formality:{type:'number'},fit:{type:'string'},confidence:{type:'number'},notes:{type:'string'}},required:['name','category','type','color','style','season','material','warmth','formality','fit','confidence','notes']};
app.post('/api/analyze-clothing',async(req,res)=>{try{const image=req.body?.image;if(!image?.startsWith('data:image/'))return res.status(400).json({error:'Изображение не получено'});res.json(await ai({name:'clothing_item',schema:clothingSchema,instructions:'Ты AI-стилист. Распознай вещь на фото. Не выдумывай бренд. warmth и formality от 1 до 5, confidence от 0 до 1. Отвечай по-русски.',input:[{role:'user',content:[{type:'input_text',text:'Распознай предмет одежды на фотографии.'},{type:'input_image',image_url:image}]}]}))}catch(e){console.error(e);res.status(500).json({error:e.message})}});
const outfitSchema={type:'object',additionalProperties:false,properties:{title:{type:'string'},itemIds:{type:'array',items:{type:'integer'}},weatherReason:{type:'string'},occasionReason:{type:'string'},styleReason:{type:'string'}},required:['title','itemIds','weatherReason','occasionReason','styleReason']};
app.post('/api/outfit',async(req,res)=>{try{const{items=[],weather=null,occasion='Повседневно'}=req.body||{};const wardrobe=items.map(x=>({id:Number(x.id),name:x.name,category:x.cat,color:x.color,style:x.style,season:x.season,type:x.type,warmth:x.warmth,formality:x.formality,fit:x.fit}));const result=await ai({name:'outfit',schema:outfitSchema,instructions:'Ты персональный стилист. Собери образ ТОЛЬКО из переданных вещей. Не придумывай вещи и ID. Учитывай погоду, ситуацию, цвета, стиль и тепло.',input:[{role:'user',content:[{type:'input_text',text:JSON.stringify({wardrobe,weather,occasion})}]}]});const allowed=new Set(wardrobe.map(x=>x.id));result.itemIds=result.itemIds.filter(id=>allowed.has(id));res.json(result)}catch(e){console.error(e);res.status(500).json({error:e.message})}});
const analysisSchema={type:'object',additionalProperties:false,properties:{score:{type:'integer'},summary:{type:'string'},good:{type:'array',items:{type:'string'}},bad:{type:'array',items:{type:'string'}},duplicates:{type:'array',items:{type:'string'}},missing:{type:'array',items:{type:'string'}},shopping:{type:'array',items:{type:'string'}}},required:['score','summary','good','bad','duplicates','missing','shopping']};
app.post('/api/analyze-wardrobe',async(req,res)=>{try{const items=(req.body?.items||[]).map(x=>({id:Number(x.id),name:x.name,category:x.cat,color:x.color,style:x.style,season:x.season,type:x.type,material:x.material,warmth:x.warmth,formality:x.formality,fit:x.fit}));const result=await ai({name:'wardrobe_analysis',schema:analysisSchema,instructions:'Проанализируй гардероб. Найди сочетания, конфликты, дубли, пробелы и разумные покупки. Не придумывай отсутствующие вещи. score 0-100.',input:[{role:'user',content:[{type:'input_text',text:JSON.stringify(items)}]}]});result.score=Math.max(0,Math.min(100,Math.round(result.score)));res.json(result)}catch(e){console.error(e);res.status(500).json({error:e.message})}});
app.get('/api/weather',async(req,res)=>{try{const lat=Number(req.query.lat),lon=Number(req.query.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))return res.status(400).json({error:'Некорректные координаты'});const u=new URL('https://api.open-meteo.com/v1/forecast');u.searchParams.set('latitude',lat);u.searchParams.set('longitude',lon);u.searchParams.set('current','temperature_2m,apparent_temperature,precipitation,rain,weather_code,wind_speed_10m');u.searchParams.set('timezone','auto');const r=await fetch(u),d=await r.json();if(!r.ok)throw Error(d.reason||'Ошибка погоды');const c=d.current,map={0:['Ясно','☀️'],1:['Преимущественно ясно','🌤️'],2:['Переменная облачность','⛅'],3:['Пасмурно','☁️'],45:['Туман','🌫️'],48:['Туман','🌫️'],51:['Морось','🌦️'],53:['Морось','🌦️'],55:['Сильная морось','🌧️'],61:['Дождь','🌧️'],63:['Дождь','🌧️'],65:['Сильный дождь','🌧️'],71:['Снег','🌨️'],73:['Снег','🌨️'],75:['Сильный снег','❄️'],80:['Ливни','🌦️'],81:['Ливни','🌧️'],82:['Сильные ливни','⛈️'],95:['Гроза','⛈️'],96:['Гроза с градом','⛈️'],99:['Гроза с градом','⛈️']};const[text,icon]=map[Number(c.weather_code)]||['Погода','🌡️'];res.json({temperature:Number(c.temperature_2m),feelsLike:Number(c.apparent_temperature),rain:Number(c.rain||0),precipitation:Number(c.precipitation||0),wind:Number(c.wind_speed_10m||0),text,icon,weatherCode:Number(c.weather_code)})}catch(e){console.error(e);res.status(500).json({error:e.message})}});
app.get('/api/health',(_req,res)=>res.json({ok:true,model:process.env.OPENAI_MODEL||null}));
app.use((req, res) => {
  res.sendFile(path.join(__dirname, 'index.html'));
});
app.listen(port,()=>console.log(`Closet AI: http://localhost:${port}`));
